/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.añadir;

import control.MascotasControlador;
import control.UsuariosControlador;
import entidades.Dueño;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edu
 */
public class UIAñadirMascota extends javax.swing.JFrame {

    DefaultTableModel tm = new DefaultTableModel();
    Dueño nuevoDueño;

    public UIAñadirMascota() {
        initComponents();
        String columnas[] = {"DNI", "Nombre", "Numero"};
        tm.setColumnIdentifiers(columnas);
        tablaDueño.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        imgTitulo = new javax.swing.JLabel();
        tfAño = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfDNI = new javax.swing.JTextField();
        tfDia = new javax.swing.JTextField();
        tfMes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDueño = new javax.swing.JTable();
        tfEspecie = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        jblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(380, 630));
        setResizable(false);

        panelContenedor.setBackground(new java.awt.Color(51, 51, 51));

        imgTitulo.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        imgTitulo.setForeground(new java.awt.Color(187, 187, 186));
        imgTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgTitulo.setText("AÑADIR MASCOTA");

        tfAño.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        tfAño.setForeground(new java.awt.Color(187, 187, 186));
        tfAño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAño.setText("Año");
        tfAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAñoActionPerformed(evt);
            }
        });

        tfNombre.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(187, 187, 186));
        tfNombre.setText("Nombre");
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfDNI.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        tfDNI.setForeground(new java.awt.Color(187, 187, 186));
        tfDNI.setText("DNI del dueño");
        tfDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDNIActionPerformed(evt);
            }
        });

        tfDia.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        tfDia.setForeground(new java.awt.Color(187, 187, 186));
        tfDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDia.setText("Dia");
        tfDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiaActionPerformed(evt);
            }
        });

        tfMes.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        tfMes.setForeground(new java.awt.Color(187, 187, 186));
        tfMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMes.setText("Mes");
        tfMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMesActionPerformed(evt);
            }
        });

        tablaDueño.setForeground(new java.awt.Color(187, 187, 186));
        tablaDueño.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(tablaDueño);

        tfEspecie.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        tfEspecie.setForeground(new java.awt.Color(187, 187, 186));
        tfEspecie.setText("Especie");
        tfEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEspecieActionPerformed(evt);
            }
        });

        btnAñadir.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        jblResultado.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        jblResultado.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEspecie, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNombre)
                            .addComponent(tfDNI)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelContenedorLayout.createSequentialGroup()
                                        .addComponent(tfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfMes)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfAño, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(imgTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(imgTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(tfEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAño, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAñoActionPerformed
        tfDNI.requestFocus();
        tfDNI.setText("");
    }//GEN-LAST:event_tfAñoActionPerformed

    private void tfDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiaActionPerformed
        tfMes.requestFocus();
        tfMes.setText("");
    }//GEN-LAST:event_tfDiaActionPerformed

    private void tfMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMesActionPerformed
        tfAño.requestFocus();
        tfAño.setText("");
    }//GEN-LAST:event_tfMesActionPerformed

    private void tfDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDNIActionPerformed

        nuevoDueño = UsuariosControlador.getDueñoDNI(tfDNI.getText());
        if (nuevoDueño != null) {
            Object[] fila = {nuevoDueño.getDni(), nuevoDueño.getNombre(), nuevoDueño.getTelefono()};
            tm.addRow(fila);
        } else {
            jblResultado.setText("¡Dueño no encontrado!");
        }
    }//GEN-LAST:event_tfDNIActionPerformed

    private void tfEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEspecieActionPerformed
        tfDia.requestFocus();
        tfDia.setText("");
    }//GEN-LAST:event_tfEspecieActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        boolean exito = MascotasControlador.agregarMascota(tfNombre.getText(), tfEspecie.getText(), Integer.parseInt(tfDia.getText()), Integer.parseInt(tfMes.getText()), Integer.parseInt(tfAño.getText()), nuevoDueño);
        if (exito) {
            System.out.println("Se añadio a la mascota");
            this.dispose();
        } else {
            jblResultado.setText("No se pudo añadir la mascota");
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        tfEspecie.requestFocus();
        tfEspecie.setText("");
    }//GEN-LAST:event_tfNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JLabel imgTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblResultado;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JTable tablaDueño;
    private javax.swing.JTextField tfAño;
    private javax.swing.JTextField tfDNI;
    private javax.swing.JTextField tfDia;
    private javax.swing.JTextField tfEspecie;
    private javax.swing.JTextField tfMes;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
