/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author edu
 */
public class PanelMascotas extends javax.swing.JPanel {

    /**
     * Creates new form Mascotas
     */
    public PanelMascotas() {
        initComponents();
        panelContenidoMascotas.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelContenidoMascotas = new javax.swing.JPanel();
        jblFondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 630));

        panelFondo.setLayout(null);

        panelContenidoMascotas.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelContenidoMascotasLayout = new javax.swing.GroupLayout(panelContenidoMascotas);
        panelContenidoMascotas.setLayout(panelContenidoMascotasLayout);
        panelContenidoMascotasLayout.setHorizontalGroup(
            panelContenidoMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        panelContenidoMascotasLayout.setVerticalGroup(
            panelContenidoMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        panelFondo.add(panelContenidoMascotas);
        panelContenidoMascotas.setBounds(0, 0, 790, 630);

        jblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/recursos/imagenes/fondo gris.jpg"))); // NOI18N
        panelFondo.add(jblFondo);
        jblFondo.setBounds(-330, 0, 1120, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblFondo;
    private javax.swing.JPanel panelContenidoMascotas;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
