/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import com.formdev.flatlaf.FlatDarkLaf;
import control.UsuariosSysControlador;

/**
 *
 * @author edu
 */
public class UIAcceso extends javax.swing.JFrame {

    private boolean usuarioClick = false;

    public UIAcceso() {
        initComponents();
        setLocationRelativeTo(null); // para que aparezca en el centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        panelNoLayout = new javax.swing.JPanel();
        imgLazy = new javax.swing.JLabel();
        imgNombre = new javax.swing.JLabel();
        imgTitulo = new javax.swing.JLabel();
        imgContraseña = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        tfContraseña = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lazy Veterinaria");
        setResizable(false);

        panelNoLayout.setLayout(null);

        imgLazy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/recursos/imagenes/lazy 430x430.jpg"))); // NOI18N
        panelNoLayout.add(imgLazy);
        imgLazy.setBounds(80, 150, 430, 430);

        imgNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/recursos/iconos/usuario.png"))); // NOI18N
        panelNoLayout.add(imgNombre);
        imgNombre.setBounds(640, 310, 32, 32);

        imgTitulo.setFont(new java.awt.Font("Fira Code", 1, 48)); // NOI18N
        imgTitulo.setForeground(new java.awt.Color(187, 187, 186));
        imgTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgTitulo.setText("LAZY VETERINARIA");
        panelNoLayout.add(imgTitulo);
        imgTitulo.setBounds(40, 50, 500, 70);

        imgContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/recursos/iconos/contraseña.png"))); // NOI18N
        panelNoLayout.add(imgContraseña);
        imgContraseña.setBounds(640, 410, 32, 32);

        tfUsuario.setBackground(new java.awt.Color(40, 41, 44));
        tfUsuario.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        tfUsuario.setForeground(new java.awt.Color(187, 187, 186));
        tfUsuario.setText("Usuario");
        tfUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfUsuarioMouseClicked(evt);
            }
        });
        tfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsuarioActionPerformed(evt);
            }
        });
        panelNoLayout.add(tfUsuario);
        tfUsuario.setBounds(700, 310, 240, 40);

        tfContraseña.setBackground(new java.awt.Color(40, 41, 44));
        tfContraseña.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        tfContraseña.setForeground(new java.awt.Color(187, 187, 186));
        tfContraseña.setText("contraseña");
        tfContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseñaActionPerformed(evt);
            }
        });
        panelNoLayout.add(tfContraseña);
        tfContraseña.setBounds(700, 400, 240, 40);

        btnIngresar.setBackground(new java.awt.Color(38, 41, 44));
        btnIngresar.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(187, 187, 186));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(null);
        btnIngresar.setBorderPainted(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        panelNoLayout.add(btnIngresar);
        btnIngresar.setBounds(770, 490, 90, 30);

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/recursos/imagenes/fondo gris.jpg"))); // NOI18N
        imgFondo.setText("jLabel2");
        panelNoLayout.add(imgFondo);
        imgFondo.setBounds(0, 0, 1120, 630);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelNoLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelNoLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsuarioActionPerformed
        tfContraseña.requestFocus();
        tfContraseña.setText("");
    }//GEN-LAST:event_tfUsuarioActionPerformed

    private void tfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseñaActionPerformed
        boolean valido = UsuariosSysControlador.validarUsuario(tfUsuario.getText(), String.valueOf(tfContraseña.getPassword()));
        iniciarDashboard(valido);
    }//GEN-LAST:event_tfContraseñaActionPerformed

    private void tfUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUsuarioMouseClicked
        if (!usuarioClick) {
            usuarioClick = true;
            return;
        }

        tfUsuario.setText("");
    }//GEN-LAST:event_tfUsuarioMouseClicked

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        boolean valido = UsuariosSysControlador.validarUsuario(tfUsuario.getText(), String.valueOf(tfContraseña.getPassword()));
        iniciarDashboard(valido);
    }//GEN-LAST:event_btnIngresarMouseClicked

    public void iniciarDashboard(boolean valido) {
        System.out.println("valido: " + valido); // esto es solo para debug
        if (valido) {
            UIDashboard dash = new UIDashboard();
            dash.setVisible(true);
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIAcceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel imgContraseña;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel imgLazy;
    private javax.swing.JLabel imgNombre;
    private javax.swing.JLabel imgTitulo;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelNoLayout;
    private javax.swing.JPasswordField tfContraseña;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
