/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import Configuracion.Configuracion;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author edu
 */
public class UIDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UIDashboard
     */
    public UIDashboard() {
        initComponents();
        setLocationRelativeTo(null); // para que aparezca en el centro
        panelMenu.setOpaque(true);
        panelMenu.setBackground(new Color(15, 15, 15, 255)); // 255 es 100%
        setPanelMascotas();
    }

    private void setPanelMascotas() {
        PanelMascotas panelMascotas = new PanelMascotas();
        panelMascotas.setSize(Configuracion.LARGO_PANEL, Configuracion.ANCHO_PANEL);
        panelMascotas.setLocation(0, 0);
        panelContenido.removeAll();
        panelContenido.add(panelMascotas, BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
        panelContenido.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        panelNoLayout = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        Mascotas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Mascotas1 = new javax.swing.JLabel();
        Mascotas2 = new javax.swing.JLabel();
        Mascotas3 = new javax.swing.JLabel();
        Mascotas4 = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();
        jblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelNoLayout.setPreferredSize(new java.awt.Dimension(1120, 630));
        panelNoLayout.setLayout(null);

        panelMenu.setBackground(new java.awt.Color(15, 15, 15));

        Mascotas.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Mascotas.setForeground(new java.awt.Color(187, 187, 186));
        Mascotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mascotas.setText("Personal");
        Mascotas.setToolTipText("");
        Mascotas.setAlignmentX(0.5F);
        Mascotas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mascotas.setEnabled(false);
        Mascotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mascotas.setPreferredSize(new java.awt.Dimension(79, 46));
        Mascotas.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 187, 186));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setEnabled(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(79, 46));
        jLabel2.setRequestFocusEnabled(false);

        Mascotas1.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Mascotas1.setForeground(new java.awt.Color(187, 187, 186));
        Mascotas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mascotas1.setText("Dueños");
        Mascotas1.setToolTipText("");
        Mascotas1.setAlignmentX(0.5F);
        Mascotas1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mascotas1.setEnabled(false);
        Mascotas1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mascotas1.setPreferredSize(new java.awt.Dimension(79, 46));
        Mascotas1.setRequestFocusEnabled(false);

        Mascotas2.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Mascotas2.setForeground(new java.awt.Color(187, 187, 186));
        Mascotas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mascotas2.setText("Citas");
        Mascotas2.setToolTipText("");
        Mascotas2.setAlignmentX(0.5F);
        Mascotas2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mascotas2.setEnabled(false);
        Mascotas2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mascotas2.setPreferredSize(new java.awt.Dimension(79, 46));
        Mascotas2.setRequestFocusEnabled(false);

        Mascotas3.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Mascotas3.setForeground(new java.awt.Color(187, 187, 186));
        Mascotas3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mascotas3.setText("Mascotas");
        Mascotas3.setToolTipText("");
        Mascotas3.setAlignmentX(0.5F);
        Mascotas3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mascotas3.setEnabled(false);
        Mascotas3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mascotas3.setPreferredSize(new java.awt.Dimension(79, 46));
        Mascotas3.setRequestFocusEnabled(false);

        Mascotas4.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Mascotas4.setForeground(new java.awt.Color(187, 187, 186));
        Mascotas4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mascotas4.setText("Productos");
        Mascotas4.setToolTipText("");
        Mascotas4.setAlignmentX(0.5F);
        Mascotas4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mascotas4.setEnabled(false);
        Mascotas4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mascotas4.setPreferredSize(new java.awt.Dimension(79, 46));
        Mascotas4.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mascotas3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mascotas1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mascotas2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mascotas4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 85, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Mascotas3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Mascotas1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Mascotas2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Mascotas4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Mascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        panelNoLayout.add(panelMenu);
        panelMenu.setBounds(0, 0, 330, 630);

        panelContenido.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        panelNoLayout.add(panelContenido);
        panelContenido.setBounds(330, 0, 790, 630);

        jblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/recursos/imagenes/fondo gris.jpg"))); // NOI18N
        panelNoLayout.add(jblFondo);
        jblFondo.setBounds(0, 0, 1120, 630);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNoLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNoLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UIDashboard().setVisible(true);
            }
        });
    }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mascotas;
    private javax.swing.JLabel Mascotas1;
    private javax.swing.JLabel Mascotas2;
    private javax.swing.JLabel Mascotas3;
    private javax.swing.JLabel Mascotas4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNoLayout;
    // End of variables declaration//GEN-END:variables
}
