/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import Configuracion.Configuracion;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author edu
 */
public class UIDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UIDashboard
     */
    public UIDashboard() {
        initComponents();
        setLocationRelativeTo(null); // para que aparezca en el centro
        panelMenu.setOpaque(true);
        panelMenu.setBackground(new Color(15, 15, 15, 255)); // 255 es 100%
        setPanelMascotas();
    }

    private void setPanelMascotas() {
        PanelMascotas panelMascotas = new PanelMascotas();
        panelMascotas.setSize(Configuracion.HORIZONTAL_PANEL, Configuracion.ALTURA_PANEL);
        panelMascotas.setLocation(0, 0);
        panelContenido.removeAll();
        panelContenido.add(panelMascotas, BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
        panelContenido.setVisible(true);
    }

    private void setPanelDueños() {
        PanelDueños panelDueños = new PanelDueños();
        panelDueños.setSize(Configuracion.HORIZONTAL_PANEL, Configuracion.ALTURA_PANEL);
        panelDueños.setLocation(0, 0);
        panelContenido.removeAll();
        panelContenido.add(panelDueños, BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
        panelContenido.setVisible(true);
    }

    private void setPanelProductos() {
        PanelProductos panelProductos = new PanelProductos();
        panelProductos.setSize(Configuracion.HORIZONTAL_PANEL, Configuracion.ALTURA_PANEL);
        panelProductos.setLocation(0, 0);
        panelContenido.removeAll();
        panelContenido.add(panelProductos, BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
        panelContenido.setVisible(true);
    }

    private void setPanelPersonal() {
        PanelPersonal panelPersonal = new PanelPersonal();
        panelPersonal.setSize(Configuracion.HORIZONTAL_PANEL, Configuracion.ALTURA_PANEL);
        panelPersonal.setLocation(0, 0);
        panelContenido.removeAll();
        panelContenido.add(panelPersonal, BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
        panelContenido.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        panelNoLayout = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        Personal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dueños = new javax.swing.JLabel();
        Mascotas2 = new javax.swing.JLabel();
        Mascotas3 = new javax.swing.JLabel();
        Productos = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();
        jblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelNoLayout.setPreferredSize(new java.awt.Dimension(1120, 630));
        panelNoLayout.setLayout(null);

        panelMenu.setBackground(new java.awt.Color(15, 15, 15));

        Personal.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Personal.setForeground(new java.awt.Color(187, 187, 186));
        Personal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Personal.setText("Personal");
        Personal.setToolTipText("");
        Personal.setAlignmentX(0.5F);
        Personal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Personal.setEnabled(false);
        Personal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Personal.setPreferredSize(new java.awt.Dimension(79, 46));
        Personal.setRequestFocusEnabled(false);
        Personal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonalMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 187, 186));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setEnabled(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(79, 46));
        jLabel2.setRequestFocusEnabled(false);

        Dueños.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Dueños.setForeground(new java.awt.Color(187, 187, 186));
        Dueños.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dueños.setText("Dueños");
        Dueños.setToolTipText("");
        Dueños.setAlignmentX(0.5F);
        Dueños.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dueños.setEnabled(false);
        Dueños.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Dueños.setPreferredSize(new java.awt.Dimension(79, 46));
        Dueños.setRequestFocusEnabled(false);
        Dueños.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DueñosMouseClicked(evt);
            }
        });

        Mascotas2.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Mascotas2.setForeground(new java.awt.Color(187, 187, 186));
        Mascotas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mascotas2.setText("Citas");
        Mascotas2.setToolTipText("");
        Mascotas2.setAlignmentX(0.5F);
        Mascotas2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mascotas2.setEnabled(false);
        Mascotas2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mascotas2.setPreferredSize(new java.awt.Dimension(79, 46));
        Mascotas2.setRequestFocusEnabled(false);

        Mascotas3.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Mascotas3.setForeground(new java.awt.Color(187, 187, 186));
        Mascotas3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mascotas3.setText("Mascotas");
        Mascotas3.setToolTipText("");
        Mascotas3.setAlignmentX(0.5F);
        Mascotas3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mascotas3.setEnabled(false);
        Mascotas3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mascotas3.setPreferredSize(new java.awt.Dimension(79, 46));
        Mascotas3.setRequestFocusEnabled(false);
        Mascotas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mascotas3MouseClicked(evt);
            }
        });

        Productos.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        Productos.setForeground(new java.awt.Color(187, 187, 186));
        Productos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Productos.setText("Productos");
        Productos.setToolTipText("");
        Productos.setAlignmentX(0.5F);
        Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Productos.setEnabled(false);
        Productos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Productos.setPreferredSize(new java.awt.Dimension(79, 46));
        Productos.setRequestFocusEnabled(false);
        Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mascotas3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dueños, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mascotas2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Personal, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 85, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Mascotas3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Dueños, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Mascotas2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Personal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        panelNoLayout.add(panelMenu);
        panelMenu.setBounds(0, 0, 330, 630);

        panelContenido.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        panelNoLayout.add(panelContenido);
        panelContenido.setBounds(330, 0, 790, 630);

        jblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/recursos/imagenes/fondo gris.jpg"))); // NOI18N
        panelNoLayout.add(jblFondo);
        jblFondo.setBounds(0, 0, 1120, 630);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNoLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNoLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DueñosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DueñosMouseClicked
        setPanelDueños();
    }//GEN-LAST:event_DueñosMouseClicked

    private void Mascotas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mascotas3MouseClicked
        setPanelMascotas();
    }//GEN-LAST:event_Mascotas3MouseClicked

    private void ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseClicked
        setPanelProductos();
    }//GEN-LAST:event_ProductosMouseClicked

    private void PersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonalMouseClicked
        setPanelPersonal();
    }//GEN-LAST:event_PersonalMouseClicked

    /*    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UIDashboard().setVisible(true);
            }
        });
    }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dueños;
    private javax.swing.JLabel Mascotas2;
    private javax.swing.JLabel Mascotas3;
    private javax.swing.JLabel Personal;
    private javax.swing.JLabel Productos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNoLayout;
    // End of variables declaration//GEN-END:variables
}
